#!/bin/sh
#
# @name NOT Applied Aeronautics Albatross
#
# @type Plane A-Tail
# @class Plane
#
# @output MAIN1 aileron right
# @output MAIN2 aileron left
# @output MAIN3 v-tail right
# @output MAIN4 v-tail left
# @output MAIN5 throttle
# @output MAIN6 wheel
# @output MAIN7 flaps right
# @output MAIN8 flaps left
#
# @output MAIN5 motor 1
# @output MAIN6 motor 2
# @output MAIN7 motor 3
# @output MAIN8 motor 4
#
# @maintainer ???
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MIN 10
	param set FW_AIRSPD_TRIM 15
	param set FW_AIRSPD_MAX 20

	param set FW_MAN_P_MAX 55
	param set FW_MAN_R_MAX 55
	param set FW_R_LIM 55

	param set FW_WR_FF 0.2
	param set FW_WR_I 0.2
	param set FW_WR_IMAX 0.8
	param set FW_WR_P 1
	param set FW_W_RMAX 0
	
		param set MC_DTERM_CUTOFF 15
	param set MC_PITCHRATE_I	0.2
	param set MC_PITCHRATE_MAX 60
	param set MC_ROLLRATE_I	0.2
	param set MC_ROLLRATE_MAX 60
	param set MC_YAWRATE_I 0.15
	param set MC_YAWRATE_MAX 40
	param set MC_YAWRATE_P 0.3

	param set MIS_TAKEOFF_ALT	30

	param set MPC_ACC_DOWN_MAX	2
	param set MPC_ACC_HOR_MAX	2
	param set MPC_ACC_UP_MAX	3
	param set MC_AIRMODE 1
	param set MPC_JERK_AUTO	8
	param set MPC_JERK_AUTO	15
	param set MPC_LAND_SPEED 1
	param set MPC_MAN_TILT_MAX 25
	param set MPC_MAN_Y_MAX 40
	param set MPC_POS_MODE 3
	param set MPC_SPOOLUP_TIME 1.5
	param set MPC_THR_HOVER 0.45
	param set MPC_TILTMAX_AIR 25
	param set MPC_TKO_RAMP_T 1.8
	param set MPC_TKO_SPEED	1
	param set MPC_VEL_MANUAL 3
	param set MPC_XY_CRUISE 3
	param set MPC_XY_VEL_MAX 3.5
	param set MPC_YAWRAUTO_MAX 40
	param set MPC_Z_VEL_MAX_DN 1.5
	param set MPC_Z_VEL_MAX_UP 2
	
	param set VT_ARSP_BLEND 10
	param set VT_ARSP_TRANS 21
	param set VT_B_DEC_MSS 1.5
	param set VT_B_TRANS_DUR 12
	param set VT_ELEV_MC_LOCK 0
	param set VT_FWD_THRUST_SC 1.2
	param set VT_FW_MOT_OFFID 5678
	param set VT_F_TR_OL_TM 8
	param set VT_IDLE_PWM_MC 1000
	param set VT_MOT_ID 5678
	param set VT_PSHER_RMP_DT 2
	param set VT_TRANS_MIN_TM 4
	param set VT_TYPE 2

	# set disarmed value for the ESC
	param set PWM_DISARMED 1000
fi

set MAV_TYPE 22
set MIXER babyshark

# use PWM parameters for throttle channel
set PWM_OUT 5
